repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies:
          [
            "fastapi>=0.115,<1.0",
            "beanie>=1.26,<3.0",
            "pydantic>=2.9,<3.0",
            "email-validator>=2.0,<3.0",
            "pydantic-settings>=2.6,<3.0",
            "pyjwt>=2.9,<3.0",
            "argon2-cffi>=23.1,<24.0",
            "python-dotenv>=1.0,<2.0",
          ]
        args: ["--config-file=pyproject.toml"]
        files: ^src/
